discount: 0.99
disclam: 1.0
num_samples: 32
action_repeat: 2
spr_coef: 2.0
spr_depth: 5
init_log_alpha: -4.0
critic_layers:
- 256
- 256
actor_layers:
- 256
- 256
hidden_dim: 128
obs_emb_dim: 64
mean_scale: 5.0
pn_number: 600
pn_layers:
- 32
- 32
- 32
- 32
pn_dropout: 0.0
rl_lr: 0.0003
ae_lr: 0.0003
dual_lr: 0.01
weight_decay: 1e-07
critic_tau: 0.995
actor_tau: 0.995
encoder_tau: 0.995
max_grad: 50.0
total_steps: 4000000
training_steps: 100
seq_len: 20
batch_size: 128
eval_freq: 20000
buffer_size: 1000
burn_in: 40
task: walker_stand
aux_loss: None
logdir: logdir
device: cuda
observe: point_cloud
